name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        type: choice
        default: info
        options:
          - debug
          - info
          - warning
          - error
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: environment
      TAGS:
        description: 'Tags'
        required: false
        type: string
      matrix:
        description: 'Matrix'
        required: true
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ${{ fromJSON(needs.dispatch.inputs.matrix)}}
    steps:
      - name: Log the inputs
        run: |
            echo "Log level: $LEVEL"
            echo "Tags: $TAGS"
            echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}